43 fetch api dom for home page
GSG-FC03/shopello pull request #53
Opened 2021-08-08 19:55 UTC by MohammadAlHabil

2021-08-08 20:17 UTC, Doaa-Abdulsalam approved these changes, later dismissed

2021-08-08 21:38 UTC, Doaa-Abdulsalam approved these changes, later dismissed

2021-08-09 03:10 UTC, MohammedHasan-99 submitted a review, later dismissed

2021-08-09 06:56 UTC, sara219 requested changes

2021-08-09 06:56 UTC, sara219 commented on home/home.js
> +    offSpan.setAttribute('class', 'nameOfTag')
![Screenshot from 2021-08-09 09-50-30](https://user-images.githubusercontent.com/47992412/128669209-28e9dc9a-0e77-44b0-8ede-b455fece7d2d.png)

something wrong with the path, what comes from the API is diff from how you save the SVG as ... where the label renders


![Screenshot from 2021-08-09 09-52-32](https://user-images.githubusercontent.com/47992412/128669381-4811d426-6a3d-4d9a-b3e3-9107bde1a82a.png)

from the API: `men's clothing.svg` 
you save it as `men's Clothing.svg`


![Screenshot from 2021-08-09 09-54-14](https://user-images.githubusercontent.com/47992412/128669587-df099bca-2296-40db-8a75-f5c2cf6b962e.png)

2021-08-09 07:48 UTC, sara219 approved these changes

2021-08-09 08:08 UTC, MohammedHasan-99 approved these changes

2021-08-09 08:10 UTC, Doaa-Abdulsalam approved these changes

2021-08-09 08:10 UTC, merged